#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Sample.Resource", IsApplication=true)]

namespace Sample
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::SharpShowcaseView.Resource.Attribute.showcaseViewStyle = global::Sample.Resource.Attribute.showcaseViewStyle;
			global::SharpShowcaseView.Resource.Attribute.sv_backgroundColor = global::Sample.Resource.Attribute.sv_backgroundColor;
			global::SharpShowcaseView.Resource.Attribute.sv_buttonBackgroundColor = global::Sample.Resource.Attribute.sv_buttonBackgroundColor;
			global::SharpShowcaseView.Resource.Attribute.sv_buttonForegroundColor = global::Sample.Resource.Attribute.sv_buttonForegroundColor;
			global::SharpShowcaseView.Resource.Attribute.sv_buttonText = global::Sample.Resource.Attribute.sv_buttonText;
			global::SharpShowcaseView.Resource.Attribute.sv_detailTextAppearance = global::Sample.Resource.Attribute.sv_detailTextAppearance;
			global::SharpShowcaseView.Resource.Attribute.sv_detailTextColor = global::Sample.Resource.Attribute.sv_detailTextColor;
			global::SharpShowcaseView.Resource.Attribute.sv_showcaseColor = global::Sample.Resource.Attribute.sv_showcaseColor;
			global::SharpShowcaseView.Resource.Attribute.sv_titleTextAppearance = global::Sample.Resource.Attribute.sv_titleTextAppearance;
			global::SharpShowcaseView.Resource.Attribute.sv_titleTextColor = global::Sample.Resource.Attribute.sv_titleTextColor;
			global::SharpShowcaseView.Resource.Drawable.btn_cling_normal = global::Sample.Resource.Drawable.btn_cling_normal;
			global::SharpShowcaseView.Resource.Drawable.btn_cling_pressed = global::Sample.Resource.Drawable.btn_cling_pressed;
			global::SharpShowcaseView.Resource.Drawable.cling = global::Sample.Resource.Drawable.cling;
			global::SharpShowcaseView.Resource.Drawable.cling_bleached = global::Sample.Resource.Drawable.cling_bleached;
			global::SharpShowcaseView.Resource.Drawable.cling_button_bg = global::Sample.Resource.Drawable.cling_button_bg;
			global::SharpShowcaseView.Resource.Drawable.hand = global::Sample.Resource.Drawable.hand;
			global::SharpShowcaseView.Resource.Id.showcase_button = global::Sample.Resource.Id.showcase_button;
			global::SharpShowcaseView.Resource.Id.showcase_sub_text = global::Sample.Resource.Id.showcase_sub_text;
			global::SharpShowcaseView.Resource.Id.showcase_title_text = global::Sample.Resource.Id.showcase_title_text;
			global::SharpShowcaseView.Resource.Layout.handy = global::Sample.Resource.Layout.handy;
			global::SharpShowcaseView.Resource.Layout.showcase_button = global::Sample.Resource.Layout.showcase_button;
			global::SharpShowcaseView.Resource.String.ok = global::Sample.Resource.String.ok;
			global::SharpShowcaseView.Resource.Style.ShowcaseButton = global::Sample.Resource.Style.ShowcaseButton;
			global::SharpShowcaseView.Resource.Style.ShowcaseView = global::Sample.Resource.Style.ShowcaseView;
			global::SharpShowcaseView.Resource.Style.ShowcaseView_Light = global::Sample.Resource.Style.ShowcaseView_Light;
			global::SharpShowcaseView.Resource.Style.TextAppearance_ShowcaseView_Detail = global::Sample.Resource.Style.TextAppearance_ShowcaseView_Detail;
			global::SharpShowcaseView.Resource.Style.TextAppearance_ShowcaseView_Detail_Light = global::Sample.Resource.Style.TextAppearance_ShowcaseView_Detail_Light;
			global::SharpShowcaseView.Resource.Style.TextAppearance_ShowcaseView_Title = global::Sample.Resource.Style.TextAppearance_ShowcaseView_Title;
			global::SharpShowcaseView.Resource.Style.TextAppearance_ShowcaseView_Title_Light = global::Sample.Resource.Style.TextAppearance_ShowcaseView_Title_Light;
			global::SharpShowcaseView.Resource.Styleable.CustomTheme = global::Sample.Resource.Styleable.CustomTheme;
			global::SharpShowcaseView.Resource.Styleable.CustomTheme_showcaseViewStyle = global::Sample.Resource.Styleable.CustomTheme_showcaseViewStyle;
			global::SharpShowcaseView.Resource.Styleable.ShowcaseView = global::Sample.Resource.Styleable.ShowcaseView;
			global::SharpShowcaseView.Resource.Styleable.ShowcaseView_sv_backgroundColor = global::Sample.Resource.Styleable.ShowcaseView_sv_backgroundColor;
			global::SharpShowcaseView.Resource.Styleable.ShowcaseView_sv_buttonBackgroundColor = global::Sample.Resource.Styleable.ShowcaseView_sv_buttonBackgroundColor;
			global::SharpShowcaseView.Resource.Styleable.ShowcaseView_sv_buttonForegroundColor = global::Sample.Resource.Styleable.ShowcaseView_sv_buttonForegroundColor;
			global::SharpShowcaseView.Resource.Styleable.ShowcaseView_sv_buttonText = global::Sample.Resource.Styleable.ShowcaseView_sv_buttonText;
			global::SharpShowcaseView.Resource.Styleable.ShowcaseView_sv_detailTextAppearance = global::Sample.Resource.Styleable.ShowcaseView_sv_detailTextAppearance;
			global::SharpShowcaseView.Resource.Styleable.ShowcaseView_sv_detailTextColor = global::Sample.Resource.Styleable.ShowcaseView_sv_detailTextColor;
			global::SharpShowcaseView.Resource.Styleable.ShowcaseView_sv_showcaseColor = global::Sample.Resource.Styleable.ShowcaseView_sv_showcaseColor;
			global::SharpShowcaseView.Resource.Styleable.ShowcaseView_sv_titleTextAppearance = global::Sample.Resource.Styleable.ShowcaseView_sv_titleTextAppearance;
			global::SharpShowcaseView.Resource.Styleable.ShowcaseView_sv_titleTextColor = global::Sample.Resource.Styleable.ShowcaseView_sv_titleTextColor;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010009
			public const int showcaseViewStyle = 2130771977;
			
			// aapt resource value: 0x7f010000
			public const int sv_backgroundColor = 2130771968;
			
			// aapt resource value: 0x7f010003
			public const int sv_buttonBackgroundColor = 2130771971;
			
			// aapt resource value: 0x7f010004
			public const int sv_buttonForegroundColor = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int sv_buttonText = 2130771973;
			
			// aapt resource value: 0x7f010006
			public const int sv_detailTextAppearance = 2130771974;
			
			// aapt resource value: 0x7f010001
			public const int sv_detailTextColor = 2130771969;
			
			// aapt resource value: 0x7f010008
			public const int sv_showcaseColor = 2130771976;
			
			// aapt resource value: 0x7f010007
			public const int sv_titleTextAppearance = 2130771975;
			
			// aapt resource value: 0x7f010002
			public const int sv_titleTextColor = 2130771970;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int bitmap = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int btn_cling_normal = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int btn_cling_pressed = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int cling = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int cling_bleached = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int cling_button_bg = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int hand = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ic_discard = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int ic_edit = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int Icon = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int kitten = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int showcase = 2130837515;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f040003
			public const int animation_textView = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int animation_textView2 = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int animation_textView3 = 2130968581;
			
			// aapt resource value: 0x7f04000d
			public const int buttonBlocked = 2130968589;
			
			// aapt resource value: 0x7f04000a
			public const int buttonFragments = 2130968586;
			
			// aapt resource value: 0x7f040008
			public const int buttonLike = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int fragment = 2130968585;
			
			// aapt resource value: 0x7f040007
			public const int image = 2130968583;
			
			// aapt resource value: 0x7f04000b
			public const int item_next_thing_textView = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public const int item_next_thing_textView2 = 2130968588;
			
			// aapt resource value: 0x7f04000e
			public const int listView = 2130968590;
			
			// aapt resource value: 0x7f04000f
			public const int menu_item1 = 2130968591;
			
			// aapt resource value: 0x7f040010
			public const int menu_item2 = 2130968592;
			
			// aapt resource value: 0x7f040000
			public const int showcase_button = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int showcase_sub_text = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int showcase_title_text = 2130968577;
			
			// aapt resource value: 0x7f040006
			public const int textView = 2130968582;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int activity_animation = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int activity_sample = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int activity_sample_legacy = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int fragment_activity_layout = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int fragment_layout = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int handy = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int item_next_thing = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Main = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int showcase_button = 2130903048;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f070000
			public const int menu = 2131165184;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050022
			public const int anim_first = 2131034146;
			
			// aapt resource value: 0x7f050023
			public const int anim_second = 2131034147;
			
			// aapt resource value: 0x7f050026
			public const int anim_third = 2131034150;
			
			// aapt resource value: 0x7f050001
			public const int app_name = 2131034113;
			
			// aapt resource value: 0x7f050003
			public const int button_blocked = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int button_hide = 2131034114;
			
			// aapt resource value: 0x7f050008
			public const int button_like = 2131034120;
			
			// aapt resource value: 0x7f05000b
			public const int dismissed_message = 2131034123;
			
			// aapt resource value: 0x7f05001c
			public const int does_really_work_with_fragments = 2131034140;
			
			// aapt resource value: 0x7f050009
			public const int error_message = 2131034121;
			
			// aapt resource value: 0x7f05001d
			public const int it_does_work = 2131034141;
			
			// aapt resource value: 0x7f05000a
			public const int like_message = 2131034122;
			
			// aapt resource value: 0x7f050000
			public const int ok = 2131034112;
			
			// aapt resource value: 0x7f050019
			public const int showcase_fragment_message = 2131034137;
			
			// aapt resource value: 0x7f050018
			public const int showcase_fragment_title = 2131034136;
			
			// aapt resource value: 0x7f050015
			public const int showcase_image_message = 2131034133;
			
			// aapt resource value: 0x7f050014
			public const int showcase_image_title = 2131034132;
			
			// aapt resource value: 0x7f050017
			public const int showcase_like_message = 2131034135;
			
			// aapt resource value: 0x7f050016
			public const int showcase_like_title = 2131034134;
			
			// aapt resource value: 0x7f05000d
			public const int showcase_main_message = 2131034125;
			
			// aapt resource value: 0x7f05000c
			public const int showcase_main_title = 2131034124;
			
			// aapt resource value: 0x7f05001b
			public const int showcase_menu_item_one_shot_message = 2131034139;
			
			// aapt resource value: 0x7f05001a
			public const int showcase_menu_item_one_shot_title = 2131034138;
			
			// aapt resource value: 0x7f050013
			public const int showcase_overflow_message = 2131034131;
			
			// aapt resource value: 0x7f050012
			public const int showcase_overflow_title = 2131034130;
			
			// aapt resource value: 0x7f05000f
			public const int showcase_simple_message = 2131034127;
			
			// aapt resource value: 0x7f05000e
			public const int showcase_simple_title = 2131034126;
			
			// aapt resource value: 0x7f050011
			public const int showcase_spinner_message = 2131034129;
			
			// aapt resource value: 0x7f050010
			public const int showcase_spinner_title = 2131034128;
			
			// aapt resource value: 0x7f05001f
			public const int sum_action_bar = 2131034143;
			
			// aapt resource value: 0x7f05001e
			public const int sum_action_items = 2131034142;
			
			// aapt resource value: 0x7f050025
			public const int sum_animations = 2131034149;
			
			// aapt resource value: 0x7f050021
			public const int sum_fragments = 2131034145;
			
			// aapt resource value: 0x7f050028
			public const int sum_memory = 2131034152;
			
			// aapt resource value: 0x7f050020
			public const int sum_multiple = 2131034144;
			
			// aapt resource value: 0x7f050005
			public const int title_action_bar = 2131034117;
			
			// aapt resource value: 0x7f050004
			public const int title_action_items = 2131034116;
			
			// aapt resource value: 0x7f050024
			public const int title_animations = 2131034148;
			
			// aapt resource value: 0x7f050007
			public const int title_fragments = 2131034119;
			
			// aapt resource value: 0x7f050027
			public const int title_memory = 2131034151;
			
			// aapt resource value: 0x7f050006
			public const int title_multiple = 2131034118;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060007
			public const int CustomShowcaseTheme = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int CustomTitle = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int ListItemBigtext = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int ListItemSubtext = 2131099658;
			
			// aapt resource value: 0x7f060000
			public const int ShowcaseButton = 2131099648;
			
			// aapt resource value: 0x7f060002
			public const int ShowcaseView = 2131099650;
			
			// aapt resource value: 0x7f060001
			public const int ShowcaseView_Light = 2131099649;
			
			// aapt resource value: 0x7f060004
			public const int TextAppearance_ShowcaseView_Detail = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int TextAppearance_ShowcaseView_Detail_Light = 2131099653;
			
			// aapt resource value: 0x7f060003
			public const int TextAppearance_ShowcaseView_Title = 2131099651;
			
			// aapt resource value: 0x7f060006
			public const int TextAppearance_ShowcaseView_Title_Light = 2131099654;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] CustomTheme = new int[] {
					2130771977};
			
			// aapt resource value: 0
			public const int CustomTheme_showcaseViewStyle = 0;
			
			public static int[] ShowcaseView = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976};
			
			// aapt resource value: 0
			public const int ShowcaseView_sv_backgroundColor = 0;
			
			// aapt resource value: 3
			public const int ShowcaseView_sv_buttonBackgroundColor = 3;
			
			// aapt resource value: 4
			public const int ShowcaseView_sv_buttonForegroundColor = 4;
			
			// aapt resource value: 5
			public const int ShowcaseView_sv_buttonText = 5;
			
			// aapt resource value: 6
			public const int ShowcaseView_sv_detailTextAppearance = 6;
			
			// aapt resource value: 1
			public const int ShowcaseView_sv_detailTextColor = 1;
			
			// aapt resource value: 8
			public const int ShowcaseView_sv_showcaseColor = 8;
			
			// aapt resource value: 7
			public const int ShowcaseView_sv_titleTextAppearance = 7;
			
			// aapt resource value: 2
			public const int ShowcaseView_sv_titleTextColor = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
